name: Main Workflow
on:
  pull_request:
jobs:
  anslint:
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
  eslint:
    runs-on: self-hosted
    needs: anslint
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Install ESLint
        run: npm install eslint
        working-directory: ./coffee-project-main
      - name: Code Linting
        run: npm run lint
        working-directory: ./coffee-project-main
  unittest:
    runs-on: self-hosted
    needs: [anslint, eslint]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
        working-directory: ./coffee-project-main
      - name: Run Tests
        run: npm run test:unit
        working-directory: ./coffee-project-main
  coverage:
    needs: [anslint, eslint, unittest]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./coffee-project-main
      - name: Run tests and generate coverage
        run: |
          coverageInfo=$(npx nyc mocha app.test.js --exit)
          coveragePercentage=$(echo "$coverageInfo" | awk '/All files/ {getline; print $3 }' | tr -d '%')
          echo "Raw Coverage Info: $coverageInfo"
          echo "Extracted Coverage Percentage: $coveragePercentage"
          if [ -n "$coveragePercentage" ] && [ "$coveragePercentage" -gt 80 ]; then
            echo "Code Coverage is above 80%. Success!!"
            exit 0
          else
            echo "Code Coverage is below 80%. Please improve Code Coverage!!"
            exit 1
          fi
        working-directory: ./coffee-project-main/test
  build:
    needs: [anslint, eslint, unittest, coverage]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Docker Compose
        run: |
          echo ${{secrets.UNIX_PASSWORD}} | sudo -S apt-get -yqq install docker-compose
      - name: Build Docker Image
        run: docker-compose build
  functional_test:
    runs-on: self-hosted
    needs: [anslint, eslint, unittest, coverage, build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
        working-directory: ./coffee-project-main
      - name: Run Tests
        run: npm run test:functional
        working-directory: ./coffee-project-main
  upload:
    needs: [anslint, eslint, unittest, coverage, build, functional_test]
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: upload image to dockerhub
        run: docker-compose push
  kubedeploy:
    needs: [anslint, eslint, unittest, coverage, build, functional_test, upload]
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Install ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: run the ansible playbook to deploy using Kubernetes
        run: ansible-playbook -i ./kube_hosts.yaml ./kube_build.yaml
